Group_5/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Group_5.Models;

namespace Group_5.Controllers
{
    public class DefaultController : Controller
    {
        public ActionResult Home()
        {
            return View();
        }
        [Authorize]

        [Route("Artist")]
        public ActionResult Artist()
        {
            ViewData["message"] = "ARTISTS";
            return View();
        }

        [Authorize]
        [Route("Exhibitions")]
        public ActionResult Exhibitions()
        {
            ViewData["message"] = "EXHIBITIONS";
            return View();
        }
        [Route("Store")]

        [Authorize]
        public ActionResult Store()
        {
            ViewData["message"] = "STORE";
            return View();
        }
        [Route("About")]
        public ActionResult About()
        {
            ViewData["message"] = "ABOUT";
            return View();
        }
        
        [HttpGet]
        public ActionResult Contact()
        {
            ViewData["message"] = "CONTACT US";
            return View();
        }
        [HttpPost]
        public ActionResult Contact(Contact cont)
        {
            if (ModelState.IsValid)
            {
                ViewBag.name = cont.Name;
                ViewBag.email = cont.Email;
                ViewBag.phone = cont.Phone;
                ViewBag.country = cont.Country;
                ViewBag.message = cont.Message;
                return View("ContactResult", cont);
            }
            else { return View(); }
        }
        
        public ActionResult ContactResult()
        {
            return View();
        }
    }
}

Group_5/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Group_5.Models;

namespace Group_5.Controllers
{
    public class SecurityController : Controller
    {
        DbPersonel db = new DbPersonel();
        [HttpGet]
        // GET: Security
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(User user)
        {
            var userInDb = db.Users.FirstOrDefault(x => x.UserName == user.UserName && x.Password == user.Password); //Is it available in the incoming user db?
            if (userInDb != null)
            {
                FormsAuthentication.SetAuthCookie(userInDb.UserName, false); //The user is now authenticated, so the pages can be browsed.
                return RedirectToAction("Home", "Default");
            }
            else
            {
                ViewBag.Message = "Invalid Username or Password";
                return View();
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Group_5/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Group_5.Models;

namespace Group_5.Controllers
{
    [Authorize]
    public class StoreManagerController : Controller
    {
        private OfferStoreDB db = new OfferStoreDB();

        // GET: StoreManager
        public ActionResult Index()
        {
            return View(db.Offers.ToList());
        }

        // GET: StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // GET: StoreManager/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StoreManager/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OfferID,Name,Phone,Email,TitleOfWork,Price")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                db.Offers.Add(offer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(offer);
        }

        // GET: StoreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: StoreManager/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OfferID,Name,Phone,Email,TitleOfWork,Price")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        // GET: StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Offer offer = db.Offers.Find(id);
            db.Offers.Remove(offer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Group_5/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/Content/CSSFiles/global.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSSFiles/header.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSSFiles/footer.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSSFiles/store.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSSFiles/contact.css" />
</head>
<body>
    <div class="img-container" style="height: initial">
        <div class="content header">
            <h2 class="logo">@Html.ActionLink("ART ON", "Home","Default")</h2>
            <ul>
                <li>@Html.ActionLink("Home", "Home","Default")</li>
                <li>@Html.ActionLink("Artist", "Artist","Default")</li>
                <li>@Html.ActionLink("Exhibitions", "Exhibitions","Default")</li>
                <li>@Html.ActionLink("Store", "Store","Default")</li>
                <li>@Html.ActionLink("About", "About","Default")</li>
                <li>@Html.ActionLink("Contact", "Contact","Default")</li>
                <li>@Html.ActionLink("Offer", "Create","StoreManager")</li>
                <li>@Html.ActionLink("Log in/out","Logout","Security")</li>
            </ul>
        </div>
    </div>

    @RenderBody()
   
    <footer>
        <div class="content">
            <div>
                <p id="copyright">Copyright © 2022 Art On</p>
                <a href="https://www.iku.edu.tr/tr/istanbulkulturuniversitesi"
                   target="_blank"
                   rel="noopener">
                    Site by Istanbul Kultur University
                </a>
            </div>
            <div>
                <a href="mailto:ogrenci.isleri@iku.edu.tr" target="_blank">
                    <img src="~/Content/Assets/images/gmail.svg"
                         alt="Gmail Logo"
                         width="30"
                         height="30" />
                </a>
                <a href="https://tr-tr.facebook.com/IKUEDU/" target="_blank">
                    <img src="~/Content/Assets/images/facebook.svg"
                         alt="Facebook Logo"
                         width="30"
                         height="30" />
                </a>
                <a href="https://twitter.com/IKUedu?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"
                   target="_blank">
                    <img src="~/Content/Assets/images/twitter.svg"
                         alt="Twitter Logo"
                         width="30"
                         height="30" />
                </a>
                <a href="https://www.instagram.com/explore/locations/880978/istanbul-kultur-universitesi/" target="_blank">
                    <img src="~/Content/Assets/images/instagram.svg"
                         alt="Instagram Logo"
                         width="30"
                         height="30" />
                </a>
            </div>
        </div>
    </footer>
</body>
</html>